### ISSUE TITLE
Typo in author_email

### ISSUE THREAD

**Issue by brisad** [jstasiak/enum-compat#1] opened 2015-07-12 20:25 UTC
Thank you for adding this package.

Got a warning when trying it out:
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'authoer_email'

**Comment by jstasiak** [comment] 2015-07-12 21:09
You're welcome. Thank you for the feedback, this is fixed and released as 0.0.2 now.

**Closed as completed by jstasiak** 2015-07-12 21:09 UTC

**Comment by robbiecrypto** [comment] 2019-03-10 18:23
https://github.com/jstasiak/enum-compat/issues/1#issuecomment-120762446 #3

**Comment by robbiecrypto** [comment] 2019-03-10 18:23
Duplicate of #
